spring:
  application:
    name: eureka-server
server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到eureka中
    fetch-registry: false       #是否从eureka中获取信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enable-self-preservation: false  #关闭自我保护
#    eviction-interval-timer-in-ms: 4000  #清理间隔
#http://www.itmuch.com/spring-cloud-sum-eureka/